apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kuard-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: kuard
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50